### ISSUE TITLE
Possible bug in RAG Tokenizer

### ISSUE THREAD

**Issue by krishanudb** [huggingface/transformers#10112]
On this line 
input_dict = tokenizer.prepare_seq2seq_batch(question, return_tensors="pt")
the following error is being generated 
AttributeError: 'super' object has no attribute 'prepare_seq2seq_batch'

**Comment by patil-suraj** [comment]
hi @krishanudb 

Thank you for reporting this @krishanudb !

**Comment by vrdn-23** [comment]
Is there any update on this issue? @patil-suraj

**Comment by patil-suraj** [comment]
It's fixed now on master!

**Comment by rajasekar-venkatesan** [comment]
The issue persists in transformers 4.3.3

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-67faa501e6b6> in <module>()
----> 1 input_dict = tokenizer.prepare_seq2seq_batch("How many people live in Paris?", "In Paris, there are 10 million people.", return_tensors="pt")
      2 input_ids = input_dict["input_ids"]

/usr/local/lib/python3.7/dist-packages/transformers/models/rag/tokenization_rag.py in prepare_seq2seq_batch(self, src_texts, tgt_texts, max_length, max_target_length, **kwargs)
     75         if max_target_length is None:
     76             max_target_length = self.generator.model_max_length
---> 77         return super().prepare_seq2seq_batch(
     78             src_texts, tgt_texts, max_length=max_length, max_target_length=max_target_length, **kwargs
     79         )

AttributeError: 'super' object has no attribute 'prepare_seq2seq_batch'

**Comment by patil-suraj** [comment]
Hi @rajasekar-venkatesan 

The issue is fixed on master after the `4.3.3` release.  This fix will be available in the next release.
