### ISSUE TITLE
PegasusTokenizer returning None

### ISSUE THREAD

**Issue by akashe** [huggingface/transformers#11789]
## Environment info

- `transformers` version:
- Platform: Ubuntu 20.04
- Python version: Python 3.7.10
- PyTorch version (GPU?): 1.8.1+cu101
- Tensorflow version (GPU?):
- Using GPU in script?: Problem in both CPU and GPU
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): Pegasus

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Go to https://huggingface.co/transformers/model_doc/pegasus.html#pegasusforconditionalgeneration
2. Run the summarization example in the section
3. PegasusTokenizer.from_pretrained('google/pegasus-xsum') returns None. PegasusTokenizer also returns None for 'google/pegasus-large'

## Expected behavior
Should return a non None value.

**Comment by patrickvonplaten** [comment]
Hey @akashe,

Think this error is analogs to this one: https://github.com/huggingface/transformers/issues/8864. 

Installing `sentencepiece` should solve the problem :-) 

https://github.com/huggingface/transformers/issues/8864

**Comment by nikhilmenon06** [comment]
> Hey @akashe,
> 
> Think this error is analogs to this one: #8864.
> 
> Installing `sentencepiece` should solve the problem :-)
> 
> #8864

Still does not seem to work, even after installing sentencepiece

**Comment by arnav7633** [comment]
Same here ;(

**Comment by akashe** [comment]
Hi @patrickvonplaten, checked with the newest transformers. Tokenizer is not returning None.

**Comment by smahm094** [comment]
@akashe did you solve the problem later? I am having the same issue.

**Comment by akashe** [comment]
Update to the newest version. It worked after that.

**Comment by Ahmedniz1** [comment]
I got the same issue first, of getting Nonetype. To solve this, just install sentencepiece, and make sure to restart runtime.
