### ISSUE TITLE
Can’t load config for ‘/data/sentence-transformers_all-mpnet-base-v2’

### ISSUE THREAD

**Issue by RohanBS** [huggingface/transformers#14572]
Hi,

I am trying to use the Accelerated Inference API and am facing this issue while using multiple sentence-transformer models. This happens when I use any input other than the auto-filled one.

![Issue](https://user-images.githubusercontent.com/24825646/144041847-8876f029-8762-41ef-9bcd-9c43fac282d5.png)

@patil-suraj @patrickvonplaten @LysandreJik

**Comment by LysandreJik** [comment]
cc @nreimers @osanseviero

**Comment by osanseviero** [comment]
This should be fixed now, it was a data corruption issue cc @Narsil

**Comment by RohanBS** [comment]
@osanseviero @Narsil Still facing this issue.

<img width="1685" alt="Screenshot 2021-12-01 at 9 47 09 AM" src="https://user-images.githubusercontent.com/24825646/144170950-f58f8496-e551-4534-9fa1-82c5b8f1107b.png">

**Comment by osanseviero** [comment]
@RohanBS sorry for the delay. The data corruption issue was fixed but the results are cached so that would explain why you were still seeing the error. I just tried this query and it seems to be working fine.
