### ISSUE TITLE
When I uesd gpt2, I got a error

### ISSUE THREAD

**Issue by ruidongtd** [huggingface/transformers#1701]
## ❓ Questions & Help

`  File "test.py", line 92, in <module>
    tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 282, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 411, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 122, in __init__
    self.encoder = json.load(open(vocab_file, encoding="utf-8"))
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ruiy/anaconda3/envs/pytorch101/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 295508 (char 295507)`

**Comment by julien-c** [comment]
We had a temporary issue with our `gpt2` model, should be fixed now.

**Comment by ruidongtd** [comment]
I reinstalled `transformers` (`pip install transformers`), and the error remains.

**Comment by ruidongtd** [comment]
> We had a temporary issue with our `gpt2` model, should be fixed now.
I reinstalled transformers (pip install transformers), and the error remains.

**Comment by ruidongtd** [comment]
> We had a temporary issue with our `gpt2` model, should be fixed now.

??

**Comment by julien-c** [comment]
use `force_download` option
