### ISSUE TITLE
Ray Release 2.7.0 breaks Trainer.hyperparameter_search 

### ISSUE THREAD

**Issue by AphinityAT** [huggingface/transformers#26314]
### System Info

When performing hyperparameter search with the ray backend, the following warning is raised and hyperparameter optimization is not performed:

```
File /ray/tune/trainable/util.py:315, in with_parameters(trainable, **kwargs)
    310 if _detect_checkpoint_function(trainable, partial=True):
    311     from ray.tune.trainable.function_trainable import (
    312         _CHECKPOINT_DIR_ARG_DEPRECATION_MSG,
    313     )
--> 315     raise DeprecationWarning(_CHECKPOINT_DIR_ARG_DEPRECATION_MSG)
    317 def inner(config):
    318     fn_kwargs = {}

DeprecationWarning: Accepting a `checkpoint_dir` argument in your training function is deprecated.
Please use `ray.train.get_checkpoint()` to access your checkpoint as a
`ray.train.Checkpoint` object instead. See below for an example:

Before
------

from ray import tune

def train_fn(config, checkpoint_dir=None):
    if checkpoint_dir:
        torch.load(os.path.join(checkpoint_dir, "checkpoint.pt"))
    ...

tuner = tune.Tuner(train_fn)
tuner.fit()

After
-----

from ray import train, tune

def train_fn(config):
    checkpoint: train.Checkpoint = train.get_checkpoint()
    if checkpoint:
        with checkpoint.as_directory() as checkpoint_dir:
            torch.load(os.path.join(checkpoint_dir, "checkpoint.pt"))
    ...

tuner = tune.Tuner(train_fn)
tuner.fit()
```

Python: 3.9
Transformers: 4.33.2
Ray: 2.7.0

**Possible Reason:**
The new Ray Release 2.7.0 changes the behavior of Checkpoints
https://github.com/ray-project/ray/releases/tag/ray-2.7.0

**Temporary Solution:**
Manually downgrade Ray to 2.6.3 

### Who can help?

@richardliaw @amogkam 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Install Ray 2.7.0
2. Run any hyperparameter code: e.g. https://huggingface.co/docs/transformers/hpo_train or https://github.com/huggingface/notebooks/blob/main/examples/text_classification.ipynb

### Expected behavior

Expected behiour is the execution of the hyperparameter search as described in the documentation or the text classification example

**Comment by vineetsharma14** [comment]
Hello,

I am encountering the same error. 


Thanks

**Comment by ArthurZucker** [comment]
The team told me that they are working on a foward fix, did not check yet but feel free to confirm!

**Comment by muellerzr** [comment]
@ArthurZucker just FYI this is linked to some failing `Trainer` tests currently as well, so once resolved those should be fixed too

**Comment by huanliang154** [comment]
Hello! Just wondering if there have been any updates to this.

**Comment by HuangLianghong** [comment]
This problem still exists in Ray-2.8.0. Are there any solutions to fix this?

**Comment by Edenzzzz** [comment]
Some one please fix it!!!

**Comment by jaanli** [comment]
Still facing this issue.

**Comment by muellerzr** [comment]
cc @justinvyu

**Comment by justinvyu** [comment]
@jaanli Are you running with `transformers>=4.36.0` where https://github.com/huggingface/transformers/pull/26499 is included?
