### ISSUE TITLE
Sphinx build for documentation fails when tensorflow is installed

### ISSUE THREAD

**Issue by venkatasg** [huggingface/transformers#3484]
## Information

I am trying to build the documentation in `docs/` using `sphinx-build` so that I can add it to [Dash](https://kapeli.com/dash) as one of the docsets. However, I get an assertion error with sphinx-build when I run `make html` in the `docs/` folder *only when tensorflow is installed*. The build works without tensorflow installed, but the tensorflow methods and classes are emtpy in the generated documentation - only the pytorch ones have documentation in the resulting HTML.

## To reproduce

1. Create a conda environment, and install pytorch, tensorflow and transformers using the official methods. 
2. Run `pip install -e ".[docs]` in source directory, before running `make html` in `docs` folder. You will get the following error (full stacktrace given later):
```
Exception occurred:
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/util/docfields.py", line 260, in transform
    assert len(field) == 2
AssertionError
```
Full stacktrace:
```
# Sphinx version: 2.4.4
# Python version: 3.6.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   reading sources... [ 13%] glossary
#   
#   reading sources... [ 16%] index
#   
#   reading sources... [ 18%] installation
#   
#   reading sources... [ 21%] main_classes/configuration
#   
#   reading sources... [ 24%] main_classes/model
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.coverage (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.napoleon (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   recommonmark (0.6.0) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/recommonmark/__init__.py
#   sphinx.ext.viewcode (2.4.4) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx_markdown_tables (<module 'sphinx_markdown_tables.__version__' from '/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx_markdown_tables/__version__.py'>) from /Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx_markdown_tables/__init__.py
Traceback (most recent call last):
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/parsers.py", line 93, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 157, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 104, in parse_generated_content
    state.nested_parse(content, 0, node)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 265, in run
    return super().run()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 195, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2374, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 265, in run
    return super().run()
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 198, in run
    DocFieldTransformer(self).transform_all(contentnode)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/util/docfields.py", line 248, in transform_all
    self.transform(child)
  File "/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx/util/docfields.py", line 260, in transform
    assert len(field) == 2
AssertionError
```
3. Uninstall tensorflow. Now when running `make html`, it does fininsh building, albeit with a bunch of warnings of the following form: `AttributeError: module 'transformers' has no attribute 'TFCamembertForMaskedLM'` -- for every `TFmethod`.

## Expected behavior

`make html` should build with no errors.

## Environment info

     
- `transformers` version: 2.6.0
- Platform: macOS 10.15.4
- Python version: 3.6.10
- PyTorch version (GPU?): 1.4.0 (No)
- Tensorflow version (GPU?): 2.1.0 (No)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No
- sphinx version: 2.4.4

**Comment by venkatasg** [comment]
This seems to be similar to [Issue #3466](https://github.com/huggingface/transformers/issues/3466)

**Comment by LysandreJik** [comment]
Hi, this issue was solved with https://github.com/huggingface/transformers/commit/e2c05f06ef58ea77103d2c64492dd8d9a0b21c3f

Could you try to pull the repository once again and try then?

**Comment by venkatasg** [comment]
Yes, that seems to have fixed it! I still get a bunch of warnings which are also related to indentation I believe? I've posted the full log of my build below with all the other warnings, but I'll close this issue for now:

```
Running Sphinx v2.4.4
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 38 source files that are out of date
updating environment: [new config] 38 added, 0 changed, 0 removed
/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] usage
/Users/venkat/Downloads/transformers/src/transformers/modeling_utils.py:docstring of transformers.PreTrainedModel.from_pretrained:23: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_utils.py:docstring of transformers.TFPreTrainedModel.from_pretrained:20: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: error while formatting arguments for transformers.pipeline: 'function' object has no attribute '__mro__'
/Users/venkat/Downloads/transformers/src/transformers/pipelines.py:docstring of transformers.Pipeline:6: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/data/processors/utils.py:docstring of transformers.data.processors.utils.DataProcessor.get_dev_examples:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/venkat/Downloads/transformers/src/transformers/data/processors/utils.py:docstring of transformers.data.processors.utils.DataProcessor.get_example_from_tensor_dict:3: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/data/processors/utils.py:docstring of transformers.data.processors.utils.DataProcessor.get_train_examples:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.batch_encode_plus:32: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.build_inputs_with_special_tokens:4: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.encode:37: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.encode_plus:36: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.prepare_for_model:17: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.prepare_for_model:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.tokenize:9: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.tokenize:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.tokenize:10: WARNING: Inline strong start-string without end-string.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_utils.py:docstring of transformers.PreTrainedTokenizer.truncate_sequences:3: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_albert.py:docstring of transformers.TFAlbertModel.call:47: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_albert.py:docstring of transformers.TFAlbertModel.call:48: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/configuration_auto.py:docstring of transformers.AutoConfig.from_pretrained:7: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_auto.py:docstring of transformers.AutoTokenizer:12: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/tokenization_auto.py:docstring of transformers.AutoTokenizer.from_pretrained:6: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModel.from_pretrained:10: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:29: WARNING: Title underline too short.

``AutoModelForPreTraining``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:29: WARNING: Title underline too short.

``AutoModelForPreTraining``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModelForPreTraining.from_pretrained:9: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:35: WARNING: Title underline too short.

``AutoModelWithLMHead``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:35: WARNING: Title underline too short.

``AutoModelWithLMHead``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModelWithLMHead.from_pretrained:10: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:41: WARNING: Title underline too short.

``AutoModelForSequenceClassification``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:41: WARNING: Title underline too short.

``AutoModelForSequenceClassification``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModelForSequenceClassification.from_pretrained:10: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:47: WARNING: Title underline too short.

``AutoModelForQuestionAnswering``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:47: WARNING: Title underline too short.

``AutoModelForQuestionAnswering``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModelForQuestionAnswering.from_pretrained:10: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:53: WARNING: Title underline too short.

``AutoModelForTokenClassification``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/auto.rst:53: WARNING: Title underline too short.

``AutoModelForTokenClassification``
~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_auto.py:docstring of transformers.AutoModelForTokenClassification.from_pretrained:10: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/docs/source/model_doc/t5.rst:7: WARNING: Title underline too short.

Overview
~~~~~
/Users/venkat/Downloads/transformers/src/transformers/tokenization_t5.py:docstring of transformers.T5Tokenizer.build_inputs_with_special_tokens:4: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5Model:9: WARNING: Duplicate explicit target name: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5Model.forward:54: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5Model.forward:55: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5ForConditionalGeneration:9: WARNING: Duplicate explicit target name: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5ForConditionalGeneration.forward:58: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5ForConditionalGeneration.forward:59: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5Model:9: WARNING: Duplicate explicit target name: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5Model:25: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5Model.call:56: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5Model.call:57: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/docs/source/model_doc/t5.rst:60: WARNING: Title underline too short.

TFT5ForConditionalGeneration
~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/docs/source/model_doc/t5.rst:60: WARNING: Title underline too short.

TFT5ForConditionalGeneration
~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5ForConditionalGeneration:9: WARNING: Duplicate explicit target name: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5ForConditionalGeneration:25: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5ForConditionalGeneration.call:60: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5ForConditionalGeneration.call:61: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5Model:1: WARNING: Duplicate target name, cannot be used as a unique reference: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_t5.py:docstring of transformers.T5ForConditionalGeneration:1: WARNING: Duplicate target name, cannot be used as a unique reference: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5Model:1: WARNING: Duplicate target name, cannot be used as a unique reference: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/modeling_tf_t5.py:docstring of transformers.TFT5ForConditionalGeneration:1: WARNING: Duplicate target name, cannot be used as a unique reference: "exploring the limits of transfer learning with a unified text-to-text transformer".
/Users/venkat/Downloads/transformers/src/transformers/configuration_xlnet.py:docstring of transformers.XLNetConfig:52: WARNING: Unexpected indentation.
/Users/venkat/Downloads/transformers/src/transformers/modeling_xlnet.py:docstring of transformers.XLNetForMultipleChoice.forward:65: WARNING: Inline literal start-string without end-string.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:25: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:29: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:36: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:40: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:44: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:48: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:52: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:56: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:60: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:64: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:68: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:73: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:78: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:82: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:86: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:90: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:94: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:152: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:156: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:160: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:164: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:168: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:172: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:176: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:180: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:184: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:188: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:192: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:196: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:200: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:207: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:211: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:215: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:219: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:223: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:227: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:231: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:235: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:239: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:264: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:268: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:272: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:276: WARNING: Line block ends without a blank line.
/Users/venkat/Downloads/transformers/docs/source/pretrained_models.rst:280: WARNING: Line block ends without a blank line.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage
/Users/venkat/Downloads/transformers/docs/source/examples.md:440: WARNING: None:any reference target not found:
generating indices...  genindexdone
highlighting module code... [100%] transformers.tokenization_xlnet
writing additional pages...  search/Users/venkat/opt/miniconda3/envs/tf-pt/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {% endblock %}
done
copying images... [100%] imgs/warmup_linear_schedule.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 107 warnings.
```

**Comment by LysandreJik** [comment]
Yes there are a few warnings, but they're inoffensive. We're working towards removing most of them :)
