### ISSUE TITLE
Recomputed tensor size does not match when using activation checkpointing when using FSDP and accelerate

### ISSUE THREAD

**Issue by jjbuck** [huggingface/transformers#34928]
### System Info

```
- `transformers` version: 4.46.3
- Platform: Linux-6.8.0-1015-aws-x86_64-with-glibc2.35
- Python version: 3.12.6
- Huggingface_hub version: 0.26.2
- Safetensors version: 0.4.5
- Accelerate version: 1.1.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.5.1+cu124 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: distributed (`accelerate`)
- Using GPU in script?: Yes
- GPU type: NVIDIA A100-SXM4-40GB
```

### Who can help?
@muellerz @SunMarc @ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm running into the following error while trying to use the SFTTrainer with FSDP and the `accelerate` library (full stack trace provided at the very bottom of this post).

```
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass
```

This occurs when I set `gradient_checkpointing: false` and `activation_checkpointing: true`. Curiously, it actually seems to work if I set `gradient_checkpointing: true` and `activation_checkpointing: false`, **but** that produces the following warning message:
```
 # When using FSDP full shard, instead of using `gradient_checkpointing` in TrainingArguments, please use `activation_checkpointing` in `fsdp_config`. The former introduces a redundant AllGather operation in backward pass. Reference: https://github.com/huggingface/transformers/issues/30404`. 
 ```

There are a few related GitHub issues around that touch on this issue:
1. https://github.com/Lightning-AI/pytorch-lightning/issues/19267
2. https://github.com/huggingface/transformers/issues/28499
3. https://github.com/pytorch/pytorch/issues/124788
4. https://github.com/huggingface/transformers/issues/32073

One of these suggested setting `use_reentrant: true`, but that doesn't resolve the issue for me.

I'm attempting to run this as a SageMaker training job using the official HuggingFace estimator (this amounts to the following command: `torchrun --nnodes 1 --nproc_per_node 8 train.py`. My training script is essentially a lightly adapted version of the official examples. Below is how I'm instantiating the HuggingFace estimator object:

```
huggingface_estimator = HuggingFace(
    entry_point          = 'train.py',        # train script
    #entry_point          = 'launch.py',        # train script
    dependencies=['requirements.txt'],         
    source_dir           = './',            
    instance_type        = 'ml.p4d.24xlarge',
    instance_count       = 1,               
    max_run              = 2*24*60*60,     
    base_job_name        = job_name,          
    role                 = role,            
    volume_size          = 1024,              
    transformers_version = '4.36.0',     
    pytorch_version      = '2.1.0',          
    py_version           = 'py310',          
    hyperparameters      =  {
        "config_s3_uri": "s3://<foo>
    },
    #metric_definitions=metric_definitions,
    disable_output_compression = True,  
    distribution={"torch_distributed": {"enabled": True}},   # enables torchrun
    environment  = {
        "HUGGINGFACE_HUB_CACHE": "/tmp/.cache", 
        "HF_TOKEN": HfFolder.get_token(),      
        "ACCELERATE_USE_FSDP": "1",             # enable FSDP
        "FSDP_CPU_RAM_EFFICIENT_LOADING": "0",   # enable CPU RAM efficient loading
        "FSDP_AUTO_WRAP_POLICY": "TRANSFORMER_BASED_WRAP",
        "FSDP_BACKWARD_PREFETCH": "BACKWARD_PRE",
        "FSDP_STATE_DICT_TYPE": "FULL_STATE_DICT",
        "NCCL_TIMEOUT": "3600",  # 1 hour timeout
        "NCCL_DEBUG": "WARN",    
        "NCCL_IB_TIMEOUT": "3600",
        "NCCL_SOCKET_TIMEOUT": "3600",
        "NCCL_ASYNC_ERROR_HANDLING": "1",
        "NCCL_P2P_LEVEL": "NVL",
        "CUDA_DEVICE_MAX_CONNECTIONS": "1",        
        "MAX_JOBS": "1",                           
        "PYTORCH_CUDA_ALLOC_CONF": "max_split_size_mb:512",
        "TORCH_DISTRIBUTED_DEBUG": "DETAIL",     
    },
    checkpoint_s3_uri=f's3://<foo>'
)
```

Below are some of the relevant parameters from my input config.
```
gradient_checkpointing: false 
gradient_checkpointing_kwargs:
  use_reentrant: true
attn_implementation: "flash_attention_2"
packing: false
bf16: "auto"
fsdp: "full_shard auto_wrap offload"
fsdp_config:
  limit_all_gathers: true
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"
  min_num_params: 0
  activation_checkpointing: "true"
```

*Full Stack Trace*
```
Traceback (most recent call last):
  File "train.py", line 224, in <module>
main(cfg)
  File "train.py", line 207, in main
    main(cfg)
  File "train.py", line 207, in main
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
Traceback (most recent call last):
  File "train.py", line 224, in <module>
main(cfg)main(cfg)
  File "train.py", line 207, in main
trainer.train()trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
return inner_training_loop(return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3612, in training_step
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3612, in training_step
tr_loss_step = self.training_step(model, inputs, num_items_in_batch)tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3612, in training_step
self.accelerator.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
Traceback (most recent call last):
  File "/opt/ml/code/train.py", line 224, in <module>
    main(cfg)
  File "/opt/ml/code/train.py", line 207, in main
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3612, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
    loss.backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1075, in unpack_hook
    frame.check_recomputed_tensors_match(gid)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 850, in check_recomputed_tensors_match
    raise CheckpointError(
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
tensor at position 18:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
tensor at position 19:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
loss.backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    loss.backward(**kwargs)
          File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
self.accelerator.backward(loss, **kwargs)self.accelerator.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1075, in unpack_hook
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1075, in unpack_hook
frame.check_recomputed_tensors_match(gid)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 850, in check_recomputed_tensors_match
        loss.backward(**kwargs)loss.backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    frame.check_recomputed_tensors_match(gid)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 850, in check_recomputed_tensors_match
        torch.autograd.backward(torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    raise CheckpointError(
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
tensor at position 18:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=2)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=2)}
tensor at position 19:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=2)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=2)}
        Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward passVariable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1075, in unpack_hook
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1075, in unpack_hook
    raise CheckpointError(
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
tensor at position 18:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
tensor at position 19:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=1)}
frame.check_recomputed_tensors_match(gid)frame.check_recomputed_tensors_match(gid)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 850, in check_recomputed_tensors_match
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 850, in check_recomputed_tensors_match
    raise CheckpointError(
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
tensor at position 18:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
tensor at position 19:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
    raise CheckpointError(
torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
tensor at position 18:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
tensor at position 19:
saved metadata: {'shape': torch.Size([2, 1024, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
recomputed metadata: {'shape': torch.Size([2, 2048, 28, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
0%|          | 0/100 [00:13<?, ?it/s]
[E ProcessGroupGloo.cpp:138] Rank 5 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
[E ProcessGroupGloo.cpp:138] Rank 4 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
[E ProcessGroupGloo.cpp:138] Rank 7 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
[2024-11-25 18:39:43,758] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 69 closing signal SIGTERM
[2024-11-25 18:39:43,758] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 73 closing signal SIGTERM
[2024-11-25 18:39:43,758] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 74 closing signal SIGTERM
[2024-11-25 18:39:43,758] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 76 closing signal SIGTERM
[2024-11-25 18:39:47,931] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 70) of binary: /opt/conda/bin/python
```

### Expected behavior

The expected behavior is for the SFTTrainer's `train()` method to run without errors.

**Comment by hav4ik** [comment]
I'm having this problem in my training as well. I'm using Deepspeed Zero3 with the trainer from transformers (although I had similar problem when I used Axolotl for another project). `use_cache` did not work for me. Setting `use_reentrant=True` did work, but the model just refuses to converge. I tested a bunch of configs, and all the settings with `use_reentrant=True` are the ones above, and `use_reentrant=False` are the ones with lower losses below.

![image](https://github.com/user-attachments/assets/dd8aaa20-d506-49b9-ab1b-9db9163eec90)

The grad norm is very strange. In the chart below, you can see a bunch of runs with very spiky grad norms, occuring every ~300 steps. These are the ones with `use_reentrant=True`. The more regular runs with OK-ish grad norms are the ones with `use_reentrant=False`.
![image](https://github.com/user-attachments/assets/24a5cfbf-cdcb-4347-b8c3-98207ea10495)

--------------------------------------

# TL;DR
Setting `use_reentrant=True` in gradients checkpointing worked, but my model just refuses to converge.

**Comment by steveepreston** [comment]
Same issue

**Comment by Smu-Tan** [comment]
> I'm having this problem in my training as well. I'm using Deepspeed Zero3 with the trainer from transformers (although I had similar problem when I used Axolotl for another project). `use_cache` did not work for me. Setting `use_reentrant=True` did work, but the model just refuses to converge. I tested a bunch of configs, and all the settings with `use_reentrant=True` are the ones above, and `use_reentrant=False` are the ones with lower losses below.
> 
> ![image](https://github.com/user-attachments/assets/dd8aaa20-d506-49b9-ab1b-9db9163eec90)
> 
> The grad norm is very strange. In the chart below, you can see a bunch of runs with very spiky grad norms, occuring every ~300 steps. These are the ones with `use_reentrant=True`. The more regular runs with OK-ish grad norms are the ones with `use_reentrant=False`. ![image](https://github.com/user-attachments/assets/24a5cfbf-cdcb-4347-b8c3-98207ea10495)
> 
> # TL;DR
> Setting `use_reentrant=True` in gradients checkpointing worked, but my model just refuses to converge.

same error here

**Comment by varad0309** [comment]
I used `use_reentrant=True` and it did converge. 

## Training
<img width="319" alt="Image" src="https://github.com/user-attachments/assets/971cf90b-5129-4ac5-9bf8-02736b52b08c" />

## Evaluation
<img width="328" alt="Image" src="https://github.com/user-attachments/assets/ba847d0d-de4f-4216-8158-446759305314" />

But I think that's it's better to deactivate gradient checkpointing for LoRA with Deepspeed Zero 3. This is because, it shards the model params as well.

**Comment by Rocketknight1** [comment]
cc @muellerzr @SunMarc

**Comment by bhattg** [comment]
Is there any update on this?

**Comment by ArthurZucker** [comment]
@bhattg do you have a full reproducer snippet? THe initial issue is fixed, `use_cache` was unproperly set to `True`, the second issue from @hav4ik or @Smu-Tan don't include any code, not a version of transformers being used

**Comment by hahmad2008** [comment]
@ArthurZucker @varad0309 @jjbuck 
can anyone help me please? I have the same issue with axolotl:
https://github.com/axolotl-ai-cloud/axolotl/discussions/2314#discussion-7925061

**Comment by steveepreston** [comment]
+1

**Comment by muellerzr** [comment]
@S1ro1 is looking into this 🤗

**Comment by wren93** [comment]
Hi, I also got the following error when using DeepSpeed Zero3 and gradient checkpointing:
```
[rank0]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
[rank0]: tensor at position 4:
[rank0]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
```

I'm trying to finetune a customized Qwen2.5VL model. Setting `use_reentrant=True` does not work for me because that will trigger another error, similar to this one: https://github.com/huggingface/transformers/issues/28623

The code will run normally if I use DeepSpeed Zero2. I have already set `use_cache=False`. Is there a fix for this issue?

**Comment by wren93** [comment]
> Hi, I also got the following error when using DeepSpeed Zero3 and gradient checkpointing:
> 
> ```
> [rank0]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
> [rank0]: tensor at position 4:
> [rank0]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> [rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> ```
> 
> I'm trying to finetune a customized Qwen2.5VL model. Setting `use_reentrant=True` does not work for me because that will trigger another error, similar to this one: [#28623](https://github.com/huggingface/transformers/issues/28623)
> 
> The code will run normally if I use DeepSpeed Zero2. I have already set `use_cache=False`. Is there a fix for this issue?

Nvm, downgrading pytorch from 2.6 to 2.2.2 seems to solve this issue.

**Comment by wavinflaghxm** [comment]
Same issue. Is there any update on this?

**Comment by SunMarc** [comment]
Please update the latest transformers, it seems that it is fixed cc @S1ro1

**Comment by S1ro1** [comment]
Yes this should be fixed in the latest transformers verion @wavinflaghxm

**Comment by JulienVig** [comment]
I still have the error after upgrading to the latest transformers version:
```
accelerate==1.6.0
torch==2.6.0
transformers==4.51.0
```
I'm using FSDP via accelerate and SFTTrainer:
```
[rank0]: tensor at position 17:
[rank0]: saved metadata: {'shape': torch.Size([1, 1024, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([1, 2048, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 18:
[rank0]: saved metadata: {'shape': torch.Size([1, 1024, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([1, 2048, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
```
The difference between the two shapes is suspicious (1024 vs 2048) as my setting uses two GPUs and a context length of 2048, it seems that somehow the sequence dimension gets halved inconsistently during activation checkpointing.
Here is my 2-GPU config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
Here are my training arguments:
```bash
accelerate launch \
    --config_file configs/fsdp_2_gpus.yaml \
    ft_fsdp.py \
    --output_dir "models/2025-04-15_17-09_Llama-3.2-3B-Instruct-ft-full" \
    --model_name "meta-llama/Llama-3.2-3B-Instruct" \
    --dataset_text_field "content" \
    --splits "train,test" \
    --seed 100 \
    --chat_template_format "none" \
    --add_special_tokens False \
    --append_concat_token False \
    --max_seq_len 2048 \
    --max_steps 2 \
    --num_train_epochs 1 \
    --logging_steps 1 \
    --log_level "info" \
    --eval_steps 100 \
    --save_steps 250 \
    --logging_strategy "steps" \
    --eval_strategy "epoch" \
    --save_strategy "epoch" \
    --bf16 True \
    --packing True \
    --learning_rate 5e-5 \
    --lr_scheduler_type "cosine" \
    --weight_decay 0.01 \
    --warmup_ratio 0.03 \
    --max_grad_norm 1.0 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_checkpointing False \
    --gradient_accumulation_steps 2 \
    --use_reentrant False \
    --use_flash_attn True \
    --ddp_timeout 5400 \
    --optim paged_adamw_32bit
```
I'm setting `fsdp_activation_checkpointing=True` in the accelerate config and `gradient_accumulation=False` in the SFTTrainer training args (and `gradient_accumulation_steps = 2`), is the correct way to do this?

**Comment by sdtblckgov** [comment]
Same error here

**Comment by MetaBlues** [comment]
Same error here

**Comment by GaotangLi** [comment]
Same error

**Comment by JusperLee** [comment]
> I still have the error after upgrading to the latest transformers version:
> 
> ```
> accelerate==1.6.0
> torch==2.6.0
> transformers==4.51.0
> ```
> 
> I'm using FSDP via accelerate and SFTTrainer:
> 
> ```
> [rank0]: tensor at position 17:
> [rank0]: saved metadata: {'shape': torch.Size([1, 1024, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> [rank0]: recomputed metadata: {'shape': torch.Size([1, 2048, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> [rank0]: tensor at position 18:
> [rank0]: saved metadata: {'shape': torch.Size([1, 1024, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> [rank0]: recomputed metadata: {'shape': torch.Size([1, 2048, 8, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> ```
> 
> The difference between the two shapes is suspicious (1024 vs 2048) as my setting uses two GPUs and a context length of 2048, it seems that somehow the sequence dimension gets halved inconsistently during activation checkpointing. Here is my 2-GPU config:
> 
> compute_environment: LOCAL_MACHINE
> debug: false
> distributed_type: FSDP
> downcast_bf16: 'no'
> enable_cpu_affinity: false
> fsdp_config:
>   fsdp_activation_checkpointing: true
>   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
>   fsdp_backward_prefetch: BACKWARD_PRE
>   fsdp_cpu_ram_efficient_loading: true
>   fsdp_forward_prefetch: false
>   fsdp_offload_params: false
>   fsdp_sharding_strategy: FULL_SHARD
>   fsdp_state_dict_type: SHARDED_STATE_DICT
>   fsdp_sync_module_states: true
>   fsdp_use_orig_params: true
> machine_rank: 0
> main_training_function: main
> mixed_precision: bf16
> num_machines: 1
> num_processes: 2
> rdzv_backend: static
> same_network: true
> tpu_env: []
> tpu_use_cluster: false
> tpu_use_sudo: false
> use_cpu: false
> Here are my training arguments:
> 
> accelerate launch \
>     --config_file configs/fsdp_2_gpus.yaml \
>     ft_fsdp.py \
>     --output_dir "models/2025-04-15_17-09_Llama-3.2-3B-Instruct-ft-full" \
>     --model_name "meta-llama/Llama-3.2-3B-Instruct" \
>     --dataset_text_field "text" \
>     --seed 100 \
>     --add_special_tokens False \
>     --append_concat_token False \
>     --max_seq_len 2048 \
>     --max_steps 2 \
>     --num_train_epochs 1 \
>     --logging_steps 1 \
>     --log_level "info" \
>     --eval_steps 100 \
>     --save_steps 250 \
>     --logging_strategy "steps" \
>     --eval_strategy "epoch" \
>     --save_strategy "epoch" \
>     --bf16 True \
>     --packing True \
>     --learning_rate 5e-5 \
>     --lr_scheduler_type "cosine" \
>     --weight_decay 0.01 \
>     --warmup_ratio 0.03 \
>     --max_grad_norm 1.0 \
>     --per_device_train_batch_size 1 \
>     --per_device_eval_batch_size 1 \
>     --gradient_checkpointing False \
>     --gradient_accumulation_steps 2 \
>     --use_reentrant False \
>     --use_flash_attn True \
>     --ddp_timeout 5400 \
>     --optim paged_adamw_32bit
> I'm setting `fsdp_activation_checkpointing=True` in the accelerate config and `gradient_checkpointing=False` in the SFTTrainer training args (and `gradient_accumulation_steps = 2`), is the correct way to do this?
> 
> Edit: it's working when I set `fsdp_activation_checkpointing=False` and `gradient_checkpointing=True`. Any idea why this is the case? When should `fsdp_activation_checkpointing` be used then?

In your fsdp_config, you have set fsdp_activation_checkpointing: true. Additionally, if the training_args.gradient_checkpointing of Transformers' Trainer is True (usually False by default, but can be enabled through parameters or model configuration), or if the model's own configuration (such as Qwen3Config) has gradient checkpointing enabled by default, it will be used.  
The error stack includes torch.utils.checkpoint.py, which confirms that gradient checkpointing is being used.

When using gradient checkpointing, certain inputs of the module are saved and then the forward pass is recomputed during backpropagation. If the state of use_cache is inconsistent during this process, or if past_key_values are incorrectly passed or saved, problems may occur.

**Comment by JulienVig** [comment]
Thank you for your answer @JusperLee.
I expect that when using FSDP, I should be setting `fsdp_activation_checkpointing=True` and `gradient_checkpointing=False` but this leads to this issue's error. Inverting both does remove the error but I expect this doesn't leverage FSDP's potential as much.
Do you have an idea on how to solve the inconsistent use_cache/past_key_values?

**Comment by ifiaposto** [comment]
> > Hi, I also got the following error when using DeepSpeed Zero3 and gradient checkpointing:
> > ```
> > [rank0]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
> > [rank0]: tensor at position 4:
> > [rank0]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> > [rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm trying to finetune a customized Qwen2.5VL model. Setting `use_reentrant=True` does not work for me because that will trigger another error, similar to this one: [#28623](https://github.com/huggingface/transformers/issues/28623)
> > The code will run normally if I use DeepSpeed Zero2. I have already set `use_cache=False`. Is there a fix for this issue?
> 
> Nvm, downgrading pytorch from 2.6 to 2.2.2 seems to solve this issue.

updated:
same. setting `use_reentrant=True`/ use_cache=False does not work . what worked was downgrading torch from 2.6 to 2.2.
my full setup is:

pip install --index-url https://download.pytorch.org/whl/cu118 \
torch==2.2.2+cu118 torchvision==0.17.2+cu118 torchaudio==2.2.2+cu118

pip install --no-deps transformers==4.54.0 trl==0.20.0

pip install \
  accelerate==1.10.0 \
  datasets==3.6.0 \
  peft==0.13.2 \
  protobuf==3.20.3 \
  einops==0.8.0 \
  tensorboard==2.20.0 \
  scikit-learn==1.5.2 \
  scipy==1.15.3 \
  numpy==1.26.4 \
  huggingface-hub==0.35.0 \
  bitsandbytes==0.47.0 \
  tokenizers==0.21.4 \
  safetensors==0.6.2

pip install deepspeed==0.14.5

**Comment by steveepreston** [comment]
>downgrading torch from 2.6 to 2.5

what a Nightmare!

**Comment by RohollahHS** [comment]
same error

transformers==4.54.0
torch==2.7.1

**Comment by juraev** [comment]
same error

torch==2.8.0+cu129
transformers==4.57.1
accelerate=1.11.0

**Comment by yurkoff-mv** [comment]
Same error
```
torch==2.9.0+cu126
transformers==4.57.1
accelerate==1.11.0
```

**Comment by ifiaposto** [comment]
@yurkoff-mv , @juraev , @RohollahHS, @SunMarc , @xf67, @steveepreston 

I made a mistake in my prev comment. Here's a setup it's actually working. I know it's not ideal but at least it's a solution!

pip install --index-url https://download.pytorch.org/whl/cu118
torch==2.2.2+cu118 torchvision==0.17.2+cu118 torchaudio==2.2.2+cu118

pip install --no-deps transformers==4.54.0 trl==0.20.0

pip install
accelerate==1.10.0
datasets==3.6.0
peft==0.13.2
protobuf==3.20.3
einops==0.8.0
tensorboard==2.20.0
scikit-learn==1.5.2
scipy==1.15.3
numpy==1.26.4
huggingface-hub==0.35.0
bitsandbytes==0.47.0
tokenizers==0.21.4
safetensors==0.6.2

pip install deepspeed==0.14.5

**Comment by steveepreston** [comment]
+1

**Comment by hardikmeisheri** [comment]
Issue is TRL library which was implicitly doing gradient check pointing. I was facing this issue without gradient checkpointing as well.

Downgrading trl==0.25.1 worked for me

**Comment by ArthurZucker** [comment]
cc @qgallouedec if you know about this!

**Comment by steveepreston** [comment]
@hardikmeisheri Downgrading a package is a nightmare. need to fix on the main line

**Comment by leobianco** [comment]
+1

**Comment by slhmath** [comment]
+1

**Comment by qgallouedec** [comment]
I can't reproduce

```python
import os
from datasets import Dataset
from trl import SFTConfig, SFTTrainer

os.environ["ACCELERATE_USE_FSDP"] = "1"
os.environ["FSDP_AUTO_WRAP_POLICY"] = "TRANSFORMER_BASED_WRAP"
os.environ["FSDP_BACKWARD_PREFETCH"] = "BACKWARD_PRE"
os.environ["FSDP_STATE_DICT_TYPE"] = "FULL_STATE_DICT"

model_id = "HuggingFaceTB/SmolLM2-135M"

# Two very different lengths to trigger dynamic-shape behavior in attention
short = "hello " * 64
long = "lorem ipsum dolor sit amet " * 600

dataset = Dataset.from_dict({"text": [short, long, short, long, short, long, short, long]})

args = SFTConfig(
    max_length=2048,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    gradient_checkpointing=False,
    fsdp="full_shard auto_wrap",
    fsdp_config={
        "activation_checkpointing": True,
        "limit_all_gathers": True,
        "backward_prefetch": "backward_pre",
        "use_orig_params": False,
    },
    packing=False,
    model_init_kwargs={"torch_dtype": "bfloat16", "attn_implementation": "kernels-community/flash-attn"},
)

trainer = SFTTrainer(
    model=model_id,
    args=args,
    train_dataset=dataset,
)

trainer.train()
```

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
num_processes: 2
mixed_precision: bf16
machine_rank: 0
num_machines: 1
fsdp_config:
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_use_orig_params: false
  fsdp_activation_checkpointing: true
```

```
accelerate launch ----config_file accelerate_fsdp.yaml 34928.py
```

works fine.

I someone has a MRE it would help investigate.
