### ISSUE TITLE
Gemma 3 Pipeline does not accept dictionary with no images

### ISSUE THREAD

**Issue by sheldonlai** [huggingface/transformers#38165]
### System Info

System info not really relevant as the bug is root caused in my description below.

- `transformers` version: 4.51.3
- Platform: Windows-10-10.0.26100-SP0
- Python version: 3.11.9
- Huggingface_hub version: 0.31.2
- Safetensors version: 0.5.3
- Accelerate version: 1.7.0
- Accelerate config:    not found
- DeepSpeed version: not installed
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script:Yes
- GPU type: NVIDIA GeForce RTX 3090

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

This issue can be created using the following snippet copied from Gemma 3 docs and up until transformer 4.51.3.
```
from transformers import pipeline
import torch

pipe = pipeline(
    "image-text-to-text",
    model="google/gemma-3-12b-it",
    device="cuda", # Or "cpu" if you don't have a compatible GPU
    torch_dtype=torch.bfloat16 # Or torch.float16 or torch.float32 based on your hardware/needs
)

messages = [
    {
        "role": "system",
        "content": [{"type": "text", "text": "You are a helpful assistant."}]
    },
    {
        "role": "user",
        "content": [
            # Removed the image link from the example
            {"type": "text", "text": "What is the capital of France?"} # Keep only the text part
        ]
    }
]

output = pipe(text=messages, max_new_tokens=200)
print(output[0]["generated_text"][-1]["content"])
```

which will result in the error:

```
Traceback (most recent call last):
  File "D:\experiments\personal\gemma_editor\gemma_editor.py", line 78, in <module>
    run_gemma(SENTENCES)
  File "D:\experiments\personal\gemma_editor\gemma_editor.py", line 41, in run_gemma
    output = pipe(text=messages)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\pipelines\image_text_to_text.py", line 311, in __call__
    return super().__call__(Chat(text, images), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\pipelines\base.py", line 1379, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\pipelines\base.py", line 1385, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\pipelines\image_text_to_text.py", line 365, in preprocess
    model_inputs = self.processor(images=images, text=text, return_tensors=self.framework, **processing_kwargs).to(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\models\gemma3\processing_gemma3.py", line 106, in __call__
    image_inputs = self.image_processor(batched_images, **output_kwargs["images_kwargs"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\image_processing_utils.py", line 42, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\utils\generic.py", line 866, in wrapper
    return func(*args, **valid_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\experiments\personal\gemma_editor\venv\Lib\site-packages\transformers\models\gemma3\image_processing_gemma3.py", line 361, in preprocess
    if do_rescale and is_scaled_image(images[0]):
                                      ~~~~~~^^^
IndexError: list index out of range
```

### Expected behavior

The problem here is that within image_text_to_text, the dictionary is made into type: Chat. [By default chat makes images an empty list](https://github.com/huggingface/transformers/blame/v4.51.3/src/transformers/pipelines/image_text_to_text.py#L114). Then this is propagated to [images](https://github.com/huggingface/transformers/blame/v4.51.3/src/transformers/pipelines/image_text_to_text.py#L353C16-L353C39) where it ultimately lands in processing_gemma_3.py where the [if condition only checks if the images are None](https://github.com/huggingface/transformers/blob/v4.51.3/src/transformers/models/gemma3/processing_gemma3.py#L102), but as we observed from the upstream code, it is set as an empty list.

It looks like in the main branch, images may no longer be set processor with Chat typed input directly, but I believe that processing_gemma3 should just handle empty list to avoid future bugs.

**Comment by khushil024** [comment]
Hi! I'd like to take this up if it's still available.

**Comment by sheldonlai** [comment]
Feel free to take it, I only fixed it in my local Libs to unblock myself.

**Comment by zucchini-nlp** [comment]
Hmm, that is weird, I remember we fixed text-only inference recently no? cc @yonigozlan

**Comment by sheldonlai** [comment]
I only examined the code up to the latest release. The problem still exists for me in 4.51.3.

In the main branch, yonigozlan did change the code in [image_text_to_text](https://github.com/huggingface/transformers/blame/main/src/transformers/pipelines/image_text_to_text.py#L335 ) 3 weeks ago, which should no longer route the Chat input to the `model_inputs = self.processor(images=images, text=text, return_tensors=self.framework, **processing_kwargs)` branch.

However, I would argue that, processing_gemma_3.py should really handle `images` that are an empty list to prevent future error.
