### ISSUE TITLE
Can't load my LoRA checkpoint after gemma3 refactor

### ISSUE THREAD

**Issue by jood-canva** [huggingface/transformers#38927]
### System Info

- `transformers` version: 4.52.4
- Platform: Linux-6.8.0-1029-aws-x86_64-with-glibc2.35
- Python version: 3.10.15
- Huggingface_hub version: 0.32.2
- Safetensors version: 0.4.3
- Accelerate version: 1.6.0
- Accelerate config: 	not found
- DeepSpeed version: not installed
- PyTorch version (GPU?): 2.6.0+cu124 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: yes but not relevant here, it happens on single gpu too
- Using GPU in script?: yes but same error on cpu only
- GPU type: NVIDIA L40S

### Who can help?

Hi @ArthurZucker and @zucchini-nlp 

I am using my own implementation of `Gemma3ForConditionalGeneration`. I was using transformers 4.50 for a while and upgraded to 4.52.4. After the update I realised that the `Gemma3ForConditionalGeneration` implementation had changed. Mostly `self.language_model` became `self.model`.

The issue is that when I use `PeftModel.from_pretrained` on my old LoRA checkpoint, it can't find the weights and I get a bunch of
```
Found missing adapter keys while loading the checkpoint: ['base_model.model.model.language_model.layers.0.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.language_model.layers.0.self_attn.q_proj.lora_B.default.weight', ...
```
I thought the `_checkpoint_conversion_mapping` [attribute](https://github.com/huggingface/transformers/blob/v4.52.4/src/transformers/models/gemma3/modeling_gemma3.py#L1236) would be enough but it isn't. Is there an easy way I can still use my old checkpoint?

Thanks in advance for you help, I really appreciate all the effort you guys make and sorry if this was explained somewhere in the documentation!

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

I have custom gemma
```
class MyCustomiGemma(Gemma3ForConditionalGeneration):
    _checkpoint_conversion_mapping = {
        "^language_model.model": "model.language_model",
        "^vision_tower": "model.vision_tower",
        "^multi_modal_projector": "model.multi_modal_projector",
        "^language_model.lm_head": "lm_head",
    }

    def __init__(
        self,
        config: Gemma3Config,
    ):
        super().__init__(config)

        self.vocab_size = config.text_config.vocab_size

        self.model = Gemma3Model(config)
        self.lm_head = nn.Linear(
            config.text_config.hidden_size, config.text_config.vocab_size, bias=False
        )

        self.another_head = nn.Linear(...)

        self.post_init()
```

When using 
```
base_model = MyCustomiGemma.from_pretrained()
model = PeftModel.from_pretrained(
              base_model,
              checkpoint_path,
              is_trainable=True,
          )
```

I get the `Found missing adapter keys while loading the checkpoint:` warning for all my LoRAs

### Expected behavior

I think the issue is just a name mapping and I thought it be backwards compatible

**Comment by zucchini-nlp** [comment]
Hey @jood-canva !

I think this was fixed in https://github.com/huggingface/transformers/pull/38627, can you try to install from `main` branch?

**Comment by jood-canva** [comment]
Hey @zucchini-nlp,

Thanks for the quick reply!
- ❌ the fix doesn't work on a vanilla `Gemma3ForConditionalGeneration`. When running this:
```
base_model = Gemma3ForConditionalGeneration.from_pretrained("google/gemma-3-12b-it", ...)
model = PeftModel.from_pretrained(
    base_model,
    <path_to_my_local_peft_ckp>,
    is_trainable=True,
)
```
I still get warnings `UserWarning: Found missing adapter keys while loading the checkpoint: ['base_model.model.model.vision_tower.vision_model.encoder.layers.0.self_attn.k_proj.lora_A.default.weight', ...`

- ❌ the fix doesn't work on a custom implementation:
```
base_model = MyCustomGemma.from_pretrained(<path_to_my_local_pretrained_folder>, ...)
model = PeftModel.from_pretrained(
    base_model,
    <path_to_my_local_peft_ckp>, # same peft checkpoint as above
    is_trainable=True,
)
```

This still gives me the `Found missing adapter keys while loading the checkpoint: [...]` warning for all layers. I don't really understand why it doesn't work...

Just checking, I have
```
transformers.__version__
'4.53.0.dev0'
```

and I made sure that my model has the _checkpoint_conversion_mapping attribute too
```
{'^language_model.model': 'model.language_model',
 '^vision_tower': 'model.vision_tower',
 '^multi_modal_projector': 'model.multi_modal_projector',
 '^language_model.lm_head': 'lm_head'}
```

Do you know what's happening?

**Comment by zucchini-nlp** [comment]
Oh you are calling `PeftModel.from_pretrained` which means it depends on peft version as well. The fix I mentioned is only on `transformers` and works for `AutoModel.from_pretrained(model_id)` wnen the `model_id` has adapters

For PEFT, I don't know if the fix was merged, cc @BenjaminBossan

**Comment by jood-canva** [comment]
@zucchini-nlp Ah ok thanks. I'm on the latest peft BTW, 0.15.2

**Comment by zucchini-nlp** [comment]
Found the PR which is here https://github.com/huggingface/peft/pull/2574#event-18276458143 and it was merged just yesterday night. So I think we'd need to wait for PEFT release or pull it from `main` branch

**Comment by BenjaminBossan** [comment]
> Found the PR which is here [huggingface/peft#2574 (comment)](https://github.com/huggingface/peft/pull/2574#event-18276458143) and it was merged just yesterday night. So I think we'd need to wait for PEFT release or pull it from `main` branch

Yes, the necessary fixes are on main but not yet released. @jood-canva if you could test with a PEFT source install and tell us if it fixes your error, that would be great.

**Comment by jood-canva** [comment]
@BenjaminBossan I tried it locally and I confirm everything works again with PEFT main 🎉 Thanks for that!
Do you know when you will release PEFT next? It would be great to have the fix as part of a release 🙏

**Comment by BenjaminBossan** [comment]
Thanks for testing, good to hear it solves the issue. I would aim for a release next week.

**Comment by jood-canva** [comment]
I confirm the issue was fixed in the latest releases of peft + transformers. Thanks for this!

**Comment by steveepreston** [comment]
Sadly I'm still getting this on the latest versions of transformers and peft!
what is the solution?

**Comment by BenjaminBossan** [comment]
_Replied in another thread._

**Comment by steveepreston** [comment]
@BenjaminBossan Thanks!

Link of issue for others: https://github.com/huggingface/peft/issues/2699
