### ISSUE TITLE
Sentiment Analysis Pipeline is predicting incorrect sentiment in 2.9

### ISSUE THREAD

**Issue by mabu-dev** [huggingface/transformers#4263]
# 🐛 Bug
Sentiment Analysis Pipeline is predicting incorrect sentiment. Everything seems to be NEGATIVE. 

## To reproduce

Left a Colab Notebook here for reproducing: https://colab.research.google.com/drive/1hIwyBOGFpcLMUNmaKf5UYb0wPeYb4yKS?usp=sharing

`pip install -qU transformers`

`from transformers import pipeline`
`sentiment_model29 = pipeline('sentiment-analysis')`
`sentiment_model29('I hate this movie')`
Returns: [{'label': 'NEGATIVE', 'score': 0.703369677066803}]

**Comment by xiaolin-cheng** [comment]
This PR should fix the problem:
https://github.com/huggingface/transformers/pull/4264

A mismatched tokenizer is hooked up with the pipeline.

**Comment by soheiltehranipour** [comment]
yes, you are right. 

I also tested all sentences both positive and negative. But it is showing NEGATIVE all the time.

**Comment by mabu-dev** [comment]
> This PR should fix the problem:
> #4264
> 
> A mismatched tokenizer is hooked up with the pipeline.

This PR didn't resolve the issue. I pulled from master but behaviour still the same. Have you tested?

**Comment by nlpravi** [comment]
Yes, I'm always getting NEGATIVE class regardless of the text

**Comment by Shubham619** [comment]
Same issue...incorrect sentiment for "nlp("i hate you")" shows [{'label': 'POSITIVE', 'score': 0.536677360534668}]

**Comment by abmitra84** [comment]
in 3.1, I always get label="POSITIVE". Must be a bug somewhere

**Comment by vishwa30** [comment]
I get Positive label with high score(0.99) for neutral statements like "This is just a statement" or "My name is this".
I don't know whats wrong. I used the base example.
from transformers import pipeline
sentiment_model = pipeline('sentiment-analysis')
sentiment_model('This is just a statement.')
