### ISSUE TITLE
SummarizationPipeline crashes

### ISSUE THREAD

**Issue by julien-c** [huggingface/transformers#4504]
```python
summarize = pipeline("summarization")
summarize("Sam Shleifer writes the best docstring examples in the whole world.")
```
➡️
```
/usr/local/lib/python3.6/dist-packages/transformers/pipelines.py in _parse_and_tokenize(self, pad_to_max_length, *args, **kwargs)
    461         # Parse arguments
    462         inputs = self._args_parser(*args, **kwargs)
--> 463         inputs = self.tokenizer.batch_encode_plus(
    464             inputs, add_special_tokens=True, return_tensors=self.framework, pad_to_max_length=pad_to_max_length,
    465         )

AttributeError: 'dict' object has no attribute 'batch_encode_plus'
```

**Comment by dalonlobo** [comment]
Is this issue fixed in version 2.10.0?

**Comment by dipanjanS** [comment]
@julien-c I still get the same error when doing

```
summarizer = pipeline('summarization')
```

and using it to summarize.

However the following explicitely works for me:

```
summarizer = pipeline('summarization', model='bart-large-cnn', tokenizer='bart-large-cnn')
```

**Comment by sshleifer** [comment]
Yeah that sounds like this issue. It will be fixed in the next release or you can build from source with
```bash
git clone [this repo]
pip install -e .
```

**Comment by khalilRhouma** [comment]
> Yeah that sounds like this issue. It will be fixed in the next release or you can build from source with
> 
> ```shell
> git clone [this repo]
> pip install -e .
> ```

I have installed the package from GitHub repo but still have the same issue right now.

**Comment by Dhanasekar-S** [comment]
@sshleifer I get this error when I clone with that commit ID.
KeyError: "Unknown task summarization, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering', 'fill-mask']"
@dipanjanS  Would be great to know what configuration you used

**Comment by sshleifer** [comment]
current master should also work.

**Comment by Dhanasekar-S** [comment]
@sshleifer The kernel still crashes
Attaching the code.
```
from transformers import pipeline
import torch

!git clone https://github.com/huggingface/transformers.git
%cd transformers
`!pip` install -e ".[dev]"

#summarizer = pipeline("summarization")
summarizer = pipeline('summarization', model='facebook/bart-large-cnn', tokenizer='facebook/bart-large-cnn') ##Kernel dies after running this line
```

transformers version - 2.11.0
torch - 1.5.0

**Comment by sshleifer** [comment]
Can't replicate :(.
Can I see your `transformers-cli env` output?

**Comment by Dhanasekar-S** [comment]
How do I get that output? I'm running these on Jupyter without any virtual env

**Comment by Dhanasekar-S** [comment]
Got it.
`
- `transformers` version: 2.11.0
- Platform: Linux-4.14.181-108.257.amzn1.x86_64-x86_64-with-glibc2.9
- Python version: 3.6.10
- PyTorch version (GPU?): 1.5.0 (False)
- Tensorflow version (GPU?): 2.2.0 (False)
- Using GPU in script?: <No>
- Using distributed or parallel set-up in script?: <No>
`

**Comment by Dhanasekar-S** [comment]
@sshleifer It works finally. There was a problem with GPU allocation. Thanks for your response.
