### ISSUE TITLE
Truncated last sentence after bart finetuning on custom dataset.

### ISSUE THREAD

**Issue by sajastu** [huggingface/transformers#6502]
- `transformers` version: 3.0.2
- Platform:
- Python version: 3.6
- PyTorch version (GPU?): 1.4
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Single GPU

### Who can help
@sshleifer

## Information

Model I am using (Bert, XLNet ...): BART

The problem arises when using:
* [x] the official example scripts: (give details below)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Finetuning BART-large-xsum on my custom dataset with differing configs: min_length=590, max_length=620.
2. Doing inference on the trained model.
3. Sentences (specifically, last sentence) that BART produces oftentimes (~90% of the cases) is incomplete. 

## Expected behavior

I would expect to have a complete and neat output, without having truncated outputs. Should mention that when I do the inference on the raw bart-large-cnn (or -xsum) checkpoint, I do not see this problem and all the outputs are complete. It sounds to me that finetuned-bart on custom dataset is not able to emit <EOS> token.

I also checked this thread: https://github.com/huggingface/transformers/issues/5674 which faces the same problem, but couldn't find the answer.

**Comment by sshleifer** [comment]
What was your training command?

**Comment by sajastu** [comment]
I used the `finetune_tiny_bart.sh` script in the seq2seq examples.

**Comment by sshleifer** [comment]
I've never really trained with such large length parameters, but we have been seeing similar problems for many models. I think these are the lines causing the issue, will try to get a fix soon.
https://github.com/huggingface/transformers/blob/master/examples/seq2seq/finetune.py#L144

**Comment by sshleifer** [comment]
I would love to replicate (need data) or have one of you test on the branch with my proposed fix:

https://github.com/huggingface/transformers/pull/6654

```bash
git fetch
git checkout batch-parity-cleaner
```

**Comment by sshleifer** [comment]
That branch is broken right now, I will comment when it's fixed.

**Comment by sshleifer** [comment]
Should work now!

**Comment by amanpreet692** [comment]
Hey,
Was trying out your branch, the earlier version atleast ran fine.
After pulling the latest like you mentioned...getting back this:
  f"Mbart is using sequence lengths {self.max_source_length}, {self.max_target_length}. "
Validation sanity check: 0it [00:00, ?it/s]Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.

I assume this has to do with the translation code? Any suggestions how to get around this?

**Comment by sshleifer** [comment]
Fixed on the branch for me, sorry about that!

**Comment by amanpreet692** [comment]
So...should I try now?

**Comment by sshleifer** [comment]
Yah!

**Comment by amanpreet692** [comment]
Still the same :(

**Comment by sshleifer** [comment]
OK. Which dataset are you using?

**Comment by amanpreet692** [comment]
I am using a custom dataset but you can try with BillSum as well and you should be able to reproduce the issue.
And btw here I was talking about this particular issue:
> Hey,
> Was trying out your branch, the earlier version atleast ran fine.
> After pulling the latest like you mentioned...getting back this:
> f"Mbart is using sequence lengths {self.max_source_length}, {self.max_target_length}. "
> Validation sanity check: 0it [00:00, ?it/s]Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> Keyword arguments {'src_lang': None, 'tgt_lang': None} not recognized.
> 
> I assume this has to do with the translation code? Any suggestions how to get around this?

I am not able to start training itself with your branch.
Let me know if you need anymore info.

**Comment by sshleifer** [comment]
Yes a training command I can paste into my terminal to run on billsum and reproduce your failure.

**Comment by amanpreet692** [comment]
I just tried this and got the same:
`./finetune.sh \
    --data_dir "../../../BillSum" \
    --train_batch_size=2 \
    --eval_batch_size=8 \
    --output_dir="/content/models/t5_narrative_512/" \
    --num_train_epochs 2 \
    --model_name_or_path="t5-base" --n_val 1000 \
    --val_check_interval 0.5 \
    --max_source_length=512 --max_target_length=150 --val_max_target_length=150 --test_max_target_length=150 \`

**Comment by sshleifer** [comment]
@patil-suraj we think these should be fixed both for t5 and bart, right?

**Comment by patil-suraj** [comment]
Yes, these issues are fixed now. @amanpreet692  could you try this with the latest master branch ?

**Comment by yxyzzz** [comment]
I used distilbart:

`tokenizer_dbart = BartTokenizer.from_pretrained('sshleifer/distilbart-cnn-6-6')`
`model_dbart = BartForConditionalGeneration.from_pretrained('sshleifer/distilbart-cnn-6-6')`

The last sentence of the summary obtained from the model is sometimes truncated.

**Comment by amanpreet692** [comment]
@patil-suraj Sorry I got back to this only now, I checked out the latest from repo today and ran finetune.sh for finetuning and could still see this issue,
eg. 
Research on inventory risk management based on abc analysis. The traditional ABC analysis is a kind of management method from the ABC curve. ABC curve is also called Pareto (Pareto) curve. The basic idea is, " vital few and the majority of the general ". In all the inventory, the cumulative percentage of species ranged from 5% to 15% and the average amount of funds occupied the cumulative percentages of 60% ~ 80% items identified as A class; the cumulative proportion of funds is 20% ~ 30% of the goods, identified as B class; and the rest as class C. The different objects use different management methods and means. In the China's enterprises,

**Comment by patil-suraj** [comment]
Hi @amanpreet692,
Could you post the arguments you are passing to `generate` ? for ex. `num_beams, max_length, length_penalty` etc ?

**Comment by amanpreet692** [comment]
Hey, I haven't tinker with the arguments to generate so I guess they should be the same as in config for distilbart:
"early_stopping": true,
"length_penalty": 2.0,
"max_length": 142,
"min_length": 56,
"no_repeat_ngram_size": 3,
"num_beams": 4
Let me know if you need anything else.
