### ISSUE TITLE
PegasusForConditionalGeneration - Error in loading state dictionary

### ISSUE THREAD

**Issue by suchig** [huggingface/transformers#6609]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Linux-5.3.0-1034-azure-x86_64-with-debian-buster-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed
- Using GPU in script?: Tried both
- Using distributed or parallel set-up in script?: No

### Who can help
@sshleifer

## Information

Model I am using (Bert, XLNet ...): google/pegasus-arxiv

The problem arises when using:
the official example scripts: 

The tasks I am working on is:
generating summary using pegasus-arxiv

## To reproduce

run the below script
```ruby
mname = "google/pegasus-arxiv"
model = PegasusForConditionalGeneration.from_pretrained(mname)
```

This is throwing error
 File "abstractive_summarizer.py", line 21, in <module>
    model = PegasusForConditionalGeneration.from_pretrained(mname, force_download=True)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/transformers/modeling_utils.py", line 894, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
	size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for model.decoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).

## Expected behavior
I tried running a sample in console this morning and it worked fine and I was able to generate summary using pegasus-arxiv. Once I transferred this to Jupyter notebook for some trial purpose, it downloaded pegasus-arxiv and after the same has been giving this error.

(If not able to simulate, please try with force_download=True)

**Comment by sshleifer** [comment]
I just fixed. Can you try again. Should produce a warning but no error.

**Comment by suchig** [comment]
I tried just now. And i got the same error

RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
	size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for model.decoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).

**Comment by suchig** [comment]
I copied the four files that were changed and tried again. I still get the same error

RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
	size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for model.decoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).

**Comment by suchig** [comment]
> I just fixed. Can you try again. Should produce a warning but no error.

RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
	size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for model.decoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).

**Comment by sshleifer** [comment]
I changed the state dict and deleted `model.encoder.embed_positions.weight` at 6pm EST.

Your code works for me on master (93c5c9a5) 

command: `transformers-cli env`

```
- `transformers` version: 3.0.2
- Platform: Darwin-19.5.0-x86_64-i386-64bit
- Python version: 3.7.7
- PyTorch version (GPU?): 1.5.1 (False)
- Tensorflow version (GPU?): 2.2.0 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by suchig** [comment]
> `model.encoder.embed_positions.weight`

I completely removed transformers and took a fresh git and I am still getting the same error. Is there some other information I could provide that will help resolve this issue for me?

**Comment by suchig** [comment]
> I changed the state dict and deleted `model.encoder.embed_positions.weight` at 6pm EST.
> 
> Your code works for me on master ([93c5c9a](https://github.com/huggingface/transformers/commit/93c5c9a528475db73c2b481131578b8dd903efba))
> 
> command: `transformers-cli env`
> 
> ```
> - `transformers` version: 3.0.2
> - Platform: Darwin-19.5.0-x86_64-i386-64bit
> - Python version: 3.7.7
> - PyTorch version (GPU?): 1.5.1 (False)
> - Tensorflow version (GPU?): 2.2.0 (False)
> - Using GPU in script?: <fill in>
> - Using distributed or parallel set-up in script?: <fill in>
> ```

The error occurs only for pegasus-arxiv. It works with warning for pegasus-pubmed and pegasus-large. I need help with pegasus-arxiv.
