### ISSUE TITLE
Sentence transformer Segmentation Fault - Pytorch 1.4.0, 2.80

### ISSUE THREAD

**Issue by elangovana** [huggingface/transformers#8206]
## Environment info

     
- `transformers` version:
- Platform: Linux
- Python version:  3.7
- PyTorch version (GPU?):  1.4 (Both)
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Doesn't Matter

### Who can help
@LysandreJik 

## Information

Model I am using (Bert):

The problem arises when using:
* [ ] the official example scripts: (give details below)

## To reproduce

1. Open python console, with torch 1.4 installed

```python
import transformers
```

This crashes with error
```text
segementation fault
```

## Expected behavior
Works as normal without error

The only way to fix this is to force install sentencepiece==0.1.91 . The root cause is that https://github.com/huggingface/transformers/blob/v2.8.0/setup.py doesn't fix the version of sentencepiece.

**Comment by thomwolf** [comment]
This will also be fixed by #8073

**Comment by prajjwal1** [comment]
I'm on `Pytorch` 1.7, downgraded `sentencepiece` to 0.1.91. Still getting this error.
